import * as THREE from 'three'
import './style.css'
import { BLOCKS, CHUNK, HEIGHT, SIZE, World, hashSeed } from './world'
import { exportWorld, importWorld, loadWorld, resetWorld, saveWorld, WorldSave } from './storage'

const app=document.querySelector<HTMLDivElement>('#app')!
app.innerHTML=`<div id="start" class="panel desktop"><div class="card"><h1 class="logo">BLOCK<br>BLOOM</h1><p class="tag">작은 섬, 커다란 상상.</p><div class="buttons"><button id="play">월드 시작</button><button id="new" class="secondary">새 월드</button><button id="export" class="secondary">내보내기</button><label class="file-label">가져오기<input id="import" type="file" accept="application/json" hidden></label></div><p class="help">WASD 이동 · SPACE 점프 · 마우스 시점<br>좌클릭 제거 · 우클릭 설치 · 1–9 / 휠 블록 선택 · ESC 메뉴</p></div></div><div class="panel mobile"><div class="card"><h1 class="logo">BLOCK BLOOM</h1><p>이 작은 세계는 키보드와 마우스가 있는 PC에서 플레이해 주세요.</p></div></div><div id="crosshair" class="desktop hidden"></div><div id="hotbar" class="hotbar desktop hidden"></div>`

const scene=new THREE.Scene();scene.background=new THREE.Color(0x8ed8ee);scene.fog=new THREE.Fog(0x8ed8ee,28,72)
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.08,100);camera.rotation.order='YXZ'
const renderer=new THREE.WebGLRenderer({antialias:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);app.prepend(renderer.domElement)
scene.add(new THREE.HemisphereLight(0xdff8ff,0x537044,2.1));const sun=new THREE.DirectionalLight(0xfff3cf,2.2);sun.position.set(25,45,15);scene.add(sun)

const colors=['#000','#55a958','#98613f','#777b80','#e7cc78','#a46d3f','#4d9a52','#bd6550','#e8e2cf','#e76f65']
function atlas(){const c=document.createElement('canvas');c.width=BLOCKS.length*16;c.height=16;const x=c.getContext('2d')!;for(let b=1;b<BLOCKS.length;b++){x.fillStyle=colors[b];x.fillRect(b*16,0,16,16);for(let i=0;i<30;i++){const v=((i*37+b*19)%13)-6;x.fillStyle=`rgba(${v>0?255:0},${v>0?255:0},${v>0?255:0},.09)`;x.fillRect(b*16+(i*7+b)%16,(i*11+b)%16,2,2)}}const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;t.colorSpace=THREE.SRGBColorSpace;return t}
const material=new THREE.MeshLambertMaterial({map:atlas(),vertexColors:true,side:THREE.FrontSide})
let loadError='';let data=(()=>{try{return loadWorld()}catch(err){loadError=(err as Error).message;return null}})();let world=new World(data?.seed??hashSeed(String(Date.now())),data?.changes);const spawn=data?.player??world.spawn();camera.position.set(spawn.x,spawn.y,spawn.z)
const chunks=new Map<string,THREE.Mesh>();const dirs=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]];const shade=[.82,.72,1,.55,.9,.76]
const corners=[[[1,0,0],[1,1,0],[1,1,1],[1,0,1]],[[0,0,1],[0,1,1],[0,1,0],[0,0,0]],[[0,1,1],[1,1,1],[1,1,0],[0,1,0]],[[0,0,0],[1,0,0],[1,0,1],[0,0,1]],[[1,0,1],[1,1,1],[0,1,1],[0,0,1]],[[0,0,0],[0,1,0],[1,1,0],[1,0,0]]]
function rebuild(cx:number,cz:number){const key=`${cx},${cz}`,old=chunks.get(key);if(old){scene.remove(old);old.geometry.dispose()}const p:number[]=[],n:number[]=[],u:number[]=[],col:number[]=[],ix:number[]=[];for(let x=cx*CHUNK;x<(cx+1)*CHUNK&&x<SIZE;x++)for(let z=cz*CHUNK;z<(cz+1)*CHUNK&&z<SIZE;z++)for(let y=0;y<HEIGHT;y++){const b=world.get(x,y,z);if(!b)continue;dirs.forEach((d,f)=>{if(world.get(x+d[0],y+d[1],z+d[2]))return;const base=p.length/3;for(const q of corners[f]){p.push(x+q[0],y+q[1],z+q[2]);n.push(...d);col.push(shade[f],shade[f],shade[f])}const pad=.002,lo=b/BLOCKS.length+pad,hi=(b+1)/BLOCKS.length-pad;u.push(lo,pad,lo,1-pad,hi,1-pad,hi,pad);ix.push(base,base+1,base+2,base,base+2,base+3)})}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(p,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(n,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(u,2));g.setAttribute('color',new THREE.Float32BufferAttribute(col,3));g.setIndex(ix);g.computeBoundingSphere();const m=new THREE.Mesh(g,material);m.userData.chunk=key;chunks.set(key,m);scene.add(m)}
for(let x=0;x<SIZE/CHUNK;x++)for(let z=0;z<SIZE/CHUNK;z++)rebuild(x,z)
function refresh(x:number,z:number){const cx=Math.floor(x/CHUNK),cz=Math.floor(z/CHUNK);[[cx,cz],[Math.floor((x-1)/CHUNK),cz],[Math.floor((x+1)/CHUNK),cz],[cx,Math.floor((z-1)/CHUNK)],[cx,Math.floor((z+1)/CHUNK)]].forEach(([a,b])=>{if(a>=0&&b>=0&&a<SIZE/CHUNK&&b<SIZE/CHUNK)rebuild(a,b)})}

const hot=document.querySelector('#hotbar')!;let selected=1;for(let i=1;i<=9;i++)hot.insertAdjacentHTML('beforeend',`<div class="slot" data-b="${i}"><i style="background:${colors[i]}"></i>${i} ${BLOCKS[i]}</div>`);function hotbar(){document.querySelectorAll('.slot').forEach((e,i)=>e.classList.toggle('selected',i+1===selected))}hotbar()
const keys=new Set<string>();let yaw=0,pitch=0,vy=0,onGround=false,saveTimer=0
addEventListener('keydown',e=>{keys.add(e.code);if(/^Digit[1-9]$/.test(e.code)){selected=+e.code.at(-1)!;hotbar()}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('wheel',e=>{selected=(selected-1+(e.deltaY>0?1:8))%9+1;hotbar()},{passive:true});addEventListener('mousemove',e=>{if(document.pointerLockElement!==renderer.domElement)return;yaw-=e.movementX*.0022;pitch=Math.max(-1.52,Math.min(1.52,pitch-e.movementY*.0022));camera.rotation.set(pitch,yaw,0)})
const playerBox=(x:number,y:number,z:number)=>({minX:x-.3,maxX:x+.3,minY:y-1.62,maxY:y+.18,minZ:z-.3,maxZ:z+.3});function blocked(x:number,y:number,z:number){const a=playerBox(x,y,z);for(let bx=Math.floor(a.minX);bx<=Math.floor(a.maxX-.001);bx++)for(let by=Math.floor(a.minY);by<=Math.floor(a.maxY-.001);by++)for(let bz=Math.floor(a.minZ);bz<=Math.floor(a.maxZ-.001);bz++)if(world.get(bx,by,bz))return true;return false}
function moveAxis(axis:'x'|'y'|'z',d:number){if(!d)return;const step=Math.sign(d)*.04;let left=Math.abs(d);while(left>0){const m=Math.sign(d)*Math.min(left,Math.abs(step));const next=camera.position.clone();next[axis]+=m;if(blocked(next.x,next.y,next.z)){if(axis==='y'){if(d<0)onGround=true;vy=0}return}camera.position.copy(next);left-=Math.abs(m)}}
const ray=new THREE.Raycaster();ray.far=6;function edit(remove:boolean){ray.setFromCamera(new THREE.Vector2(0,0),camera);const hit=ray.intersectObjects([...chunks.values()],false)[0];if(!hit||!hit.face)return;const q=hit.point.clone().addScaledVector(hit.face.normal,remove?-.01:.01);const x=Math.floor(q.x),y=Math.floor(q.y),z=Math.floor(q.z);if(remove&&y===0)return;if(!remove){const a=playerBox(camera.position.x,camera.position.y,camera.position.z);if(x+1>a.minX&&x<a.maxX&&y+1>a.minY&&y<a.maxY&&z+1>a.minZ&&z<a.maxZ)return}world.set(x,y,z,remove?0:selected);refresh(x,z);scheduleSave()}
renderer.domElement.addEventListener('mousedown',e=>{if(document.pointerLockElement!==renderer.domElement)return;e.preventDefault();edit(e.button===0)});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault())
function snapshot():WorldSave{return {version:1,seed:world.seed,size:{x:SIZE,y:HEIGHT,z:SIZE},player:{x:camera.position.x,y:camera.position.y,z:camera.position.z},changes:world.changes}}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=window.setTimeout(()=>saveWorld(snapshot()),350)}
const start=document.querySelector('#start')!;function play(){renderer.domElement.requestPointerLock()};document.querySelector('#play')!.addEventListener('click',play);document.addEventListener('pointerlockchange',()=>{const active=document.pointerLockElement===renderer.domElement;start.classList.toggle('hidden',active);document.querySelector('#crosshair')!.classList.toggle('hidden',!active);hot.classList.toggle('hidden',!active);if(!active)scheduleSave()})
document.querySelector('#new')!.addEventListener('click',()=>{if(confirm('현재 월드를 지우고 새 섬을 만들까요?')){resetWorld();location.reload()}});document.querySelector('#export')!.addEventListener('click',()=>exportWorld(snapshot()));document.querySelector<HTMLInputElement>('#import')!.addEventListener('change',async e=>{try{const file=(e.currentTarget as HTMLInputElement).files?.[0];if(!file)return;const s=await importWorld(file);saveWorld(s);location.reload()}catch(err){alert((err as Error).message)}})
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('beforeunload',()=>saveWorld(snapshot()));if(loadError)setTimeout(()=>{if(confirm(`${loadError}\n저장 데이터를 초기화할까요?`)){resetWorld();location.reload()}},100)
let last=performance.now();function loop(now:number){const dt=Math.min(.05,(now-last)/1000);last=now;if(document.pointerLockElement===renderer.domElement){const speed=keys.has('ShiftLeft')?7.5:5;const forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),side=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);const len=Math.hypot(forward,side)||1;moveAxis('x',(Math.sin(yaw)*-forward+Math.cos(yaw)*side)/len*speed*dt);moveAxis('z',(Math.cos(yaw)*-forward-Math.sin(yaw)*side)/len*speed*dt);if(keys.has('Space')&&onGround){vy=7;onGround=false}vy-=19*dt;onGround=false;moveAxis('y',vy*dt);if(camera.position.y<0)camera.position.set(...Object.values(world.spawn()) as [number,number,number]);scheduleSave()}renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop)
